### ISSUE TITLE
Support multiple reporters

### ISSUE THREAD

**Issue by joshuacc** [wbuchwalter/tslint-loader#10]
Related to #7: It would also be nice to be able to have a normal console reporter and a file-based reporter run at the same time. Presumably it could be done by having tslint-loader supply its own `format` method, which would then delegate to the others.

**Comment by wbuchwalter** [comment]
Is this a need that you currently have?
I can't really see a use case for this.
If you do have this need, feel free to submit a PR for this, I don't have much time currently.
I would just like to keep this loader as simple as possible.
Thanks!

**Comment by joshuacc** [comment]
@wbuchwalter It would be convenient if we could avoid having to run different builds for human readable vs machine readable output. However, I wouldn't consider it a high priority at this point.

Closing for now. Will bring it back up later if we decide we really need it.

**Comment by wbuchwalter** [comment]
Thanks :+1:
