### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by SebastianStehle** [wbuchwalter/tslint-loader#109]
Hi,

I love the functionality of this tslint-loader. But I wonder about the performance. My angular project takes ~15sec to build in the dev-server, even if I do not change a single file and just force it by saving a random file.

I tried to cache as much as possible, e.g. I turned on useCache and useBabel with awesome-typescript-loader, but it has almost no effect.

When I remove ts-lint from my loader settings, the performance is increased to 4sec. Still a little bit slow, but I can live with that. 

In theory webpack should be able to cache everything so I am confused why tslint is running so long for incremental builds.

**Comment by nfm** [comment]
@SebastianStehle see #76 if you haven't already, there's some performance related discussion there.
