### ISSUE TITLE
modules not loaded

### ISSUE THREAD

**Issue by itajaja** [wbuchwalter/tslint-loader#14]
If I have something like this:

index.ts:
````ts
export const foo: MyModule.MyFoo = null;
````

and

myFoo.ts:
````ts
module MyModule {
  export interface MyFoo { /*...*/ }
}
````

ts-loader will not check whatever errors are inside the myFoo files. This happens becuase actually myFoo.ts is not `import`ed. What's the best way to check referenced modules?

**Comment by wbuchwalter** [comment]
This is most likely an issue with [tslint](https://github.com/palantir/tslint) itself, not with the loader.
You should reopen your issue there.
Thanks.
