### ISSUE TITLE
tslint-loader doesn't handle rulesDirectory field of tslint.json correctly

### ISSUE THREAD

**Issue by JKillian** [wbuchwalter/tslint-loader#16]
If a user [specifies a path(s) to custom rule directories in their `tslint.json` file](http://palantir.github.io/tslint/usage/custom-rules/), tslint-loader does not correctly pass this to TSLint.

The issue is that the `options` object that gets passes in the line `var linter = new Linter(this.resourcePath, input, options);` is structured incorrectly.

Right now it's structured as this:
```
{
  configuration: {
    rulesDirectory: ...
  },
  ...
}
```

when the actual correct structure is like this:

```
{
  configuration: {
    rulesDirectory: ...  // it's okay if this isn't here
  },
  rulesDirectory: ...
}
```

At first this may seem like a bug on the end of TSLint - why doesn't TSLint correctly handle the first case? The issue is a little subtle - paths specified in a `tslint.json` file are relative to the location of the `tslint.json`. So TSLint has no way to resolve those paths when provided via the JS API. When TSLint loads a `tslint.json` file on its own, it can resolve the paths because it knows the location of the `tslint.json file`.

To fix this, you can use the `getRulesDirectories(paths, basePath)` function provided by TSLint to resolve paths from a `tslint.json` file and then provide the paths at the top-level of the options object

**Comment by wbuchwalter** [comment]
Fixed in `@2.1.1`, thanks!
