### ISSUE TITLE
Tslint errors are not displayed when using --bail option in Webpack

### ISSUE THREAD

**Issue by jhuntoo** [wbuchwalter/tslint-loader#18]
An issue has been encountered here
https://github.com/AngularClass/angular2-webpack-starter/issues/374

I believe it's because the --bail option is used (so that webpack returns a non-zero exit status). So webpack exits before tslint-loader has output anything to the console.

**Comment by jhuntoo** [comment]
@wbuchwalter I've created #19 which is a workaround for what is essentially webpack weirdness. See https://github.com/webpack/webpack/issues/711

**Comment by wbuchwalter** [comment]
Fixed by #19, and released in `@2.1.3`.
Thanks.
