### ISSUE TITLE
merge method turns arrays into objects

### ISSUE THREAD

**Issue by scott-yu** [wbuchwalter/tslint-loader#21]
For example, "quotemark": [ true, "single" ] will be turned into "quotemark": { 0: true, 1: "single" }. 
The abstractRule's isEnabled check would fail because it's checking to see if value is an Array with Array.isArray(value). 
These rules would be treated as disabled.

**Comment by sshev** [comment]
@wbuchwalter I've created PR with fix for this issue.
https://github.com/wbuchwalter/tslint-loader/pull/24

**Comment by wbuchwalter** [comment]
Thanks!
