### ISSUE TITLE
Specify custom tslint file

### ISSUE THREAD

**Issue by raybooysen** [wbuchwalter/tslint-loader#22]
This may already exist but could not see it in the README.md.  Is there a way to specify a custom location for the tsling.json file?  

At the moment, it'll default to tslint.json in the root, but it would be good to be able to specify a path.

Thanks for the great loader!

**Comment by dsebastien** [comment]
I'm also interested in this. I have a use case for this feature:
We're creating a shared library that will embed a generic Webpack configuration along with loaders including tslint-loader and the tslint configuration file.

The structure will look as follows:

```
<app>
|-- package.json (script to execute webpack)
|--\ node_modules
|--|--\ <shared_library>
|--|--|--\ config (contains webpack config file)
|--|--|--\ node_modules
|--|--|--|--\ tslint
|--|--|--|--\ tslint-loader
|--|--|-- tslint.json (configura

```

**Comment by nikaspran** [comment]
@dsebastien 

As a workaround, you can use the `extends` feature and create a tiny reference `tsconfig.json` in the root of the app:

```json
{
	"extends": "./node_modules/shared_library/tslint.json"
}
```

**Comment by dsebastien** [comment]
Heh, thanks a ton @nikaspran this fixed my issue entirely :)

**Comment by blacksonic** [comment]
@raybooysen now it is available with ```configFile``` https://github.com/wbuchwalter/tslint-loader/commit/df049827be5fe85c4950416deab5cdc6fcfca77e
