### ISSUE TITLE
Use findConfiguration from tslint/lib/configuration

### ISSUE THREAD

**Issue by adidahiya** [wbuchwalter/tslint-loader#23]
should be able to replace [this code in index.js](https://github.com/wbuchwalter/tslint-loader/blob/957b179d3315e13e1fdd9ac5381bdb41e07aa083/index.js#L39-L48) and fix some of the recent issues I've been experiencing with the new `extends` feature + tslint-loader

// cc @JKillian

**Comment by wbuchwalter** [comment]
Fixed with #30!
