### ISSUE TITLE
Add caching abilities.

### ISSUE THREAD

**Issue by Strate** [wbuchwalter/tslint-loader#35]
It would be good, If this loader cache to filesystem linting results and reuse them between build. Same thing implemented in babel-loader.

**Comment by pavloko** [comment]
Could the author please provide his opinion on this and maybe some direction on possible implementation? Thanks.

**Comment by wbuchwalter** [comment]
I'm fine with that, but I sadly don't have time to support this project anymore.
If someones want to do a fork, I would gladly point to it in the README.
Or if anyone wants to be added as a maintainer of this project, let me know.

**Comment by Strate** [comment]
As for now I use this plugin for cache: https://github.com/mzgoddard/hard-source-webpack-plugin. It works great and cache all build information. So, I'd suggest all to use it.
