### ISSUE TITLE
Add support for enabling type-checked rules.

### ISSUE THREAD

**Issue by skolsuper** [wbuchwalter/tslint-loader#36]
TSLint recently gained some new rules that require type-checking to be enabled.  This requires that the compiled program be passed in to the linter [like so](https://github.com/palantir/tslint#type-checking).

I'm sorry, I don't know enough (anything) about the internals of webpack or tslint so I am unable to submit a PR.  Maybe [this commit](https://github.com/panuhorsmalahti/gulp-tslint/commit/da6024a09b6d96d1b12079e47eeadde6e6c72681) from gulp-tslint will contain useful information?

**Comment by blacksonic** [comment]
Available from version 3.1.0 https://github.com/wbuchwalter/tslint-loader/commit/f63db7eaf7078bd168c96e8e2641a73d19d466e8
