### ISSUE TITLE
exclude node_modules

### ISSUE THREAD

**Issue by grauschnabel** [wbuchwalter/tslint-loader#39]
Hi there,

Is there a way to exclude the node_modules directory.  I cannot fix all the tslint issues I load with npm install ....

Thanks,
Martin

**Comment by jmlopez-rod** [comment]
You mean use `exclude` with webpack?

```
{ test: /\.ts$/i, loaders: ['ts', 'tslint'], exclude: /node_modules/ }
```

**Comment by grauschnabel** [comment]
thats it, thanks very much!
