### ISSUE TITLE
Update to TSLint 4.0

### ISSUE THREAD

**Issue by Connormiha** [wbuchwalter/tslint-loader#42]
TSLint 4.0.x already got released, see https://github.com/palantir/tslint/releases/tag/4.0.0. Yet, the update doesn't work with the latest version of tslint-loader.

`Module build failed: TypeError: Linter is not a constructor`

Are there any plans when tslint-loader will be updated?

**Comment by paralin** [comment]
Agreed, needs updating.

**Comment by blacksonic** [comment]
Merged and deployed https://github.com/wbuchwalter/tslint-loader/pull/43
Peer dependency Tslint is now 4.x
