### ISSUE TITLE
tslint-loader unexpected token

### ISSUE THREAD

**Issue by jasdf2351** [wbuchwalter/tslint-loader#44]
Ouput of webpack:

ERROR in ./server/index.ts
Module parse failed: /home/ubuntu/workspace/node_modules/tslint-loader/index.js!/home/ubuntu/workspace/server/index.ts Unexpected token (22:7)
You may need an appropriate loader to handle this file type.
| // Catch 404 and forward to error handler
| app.use((
|     req: express.Request,
|     res: express.Response,
|     next: express.NextFunction) => {

If I take out the typing, leaving it just as:
app.use((req, res, next) => {
then everything is fine.

According to the TS docs [https://www.typescriptlang.org/docs/handbook/tsconfig-json.html], I shouldn't need to do anything with the old way of installing typings, typings install etc.  I know I'm using beta for webpack but figured I'd get ahead 😄 

./package.json:
"@types/body-parser": "0.0.33",
"@types/debug": "0.0.29",
"@types/express": "4.0.34",
"@types/morgan": "1.7.32",
"@types/node": "6.0.49",
"awesome-typescript-loader": "3.0.0-beta.3",
"tslint": "3.15.1",
"tslint-loader": "2.1.5",
"typescript": "2.0.10",
"webpack": "2.1.0-beta.27"

./config/webpack.config.js:
const webpack = require('webpack');
const plugins = [];

plugins.push(
    new webpack.LoaderOptionsPlugin({
        options: {
            tslint: {
                emitErrors: true,
                failOnHint: true
            }
        }
    })
);

module.exports = {
    entry: {
        server: './bin/www.ts'
    },
    output: {
        filename: '[name].js',
        path: './build',
        libraryTarget: "commonjs"
    },
    devtool: 'source-map',
    target: 'node',
    externals: [
        /^[a-z\-0-9]+$/ // Ignore node_modules folder
    ],
    resolve: {
        // Add in `.ts` as a resolvable extension.
        extensions: ['.ts'],
    },
    resolveLoader: {
        modules: ['./node_modules']
    },
    module: {
        rules: [{
            enforce: 'pre',
            test: /\.ts$/,
            loader: 'tslint-loader',
            exclude: /(node_modules)/
        }],
        loaders: [{
            test: /\.ts$/,
            exclude: [/node_modules/],
            loader: 'awesome-typescript-loader'
        }]
    },
    plugins
};

./tsconfig.json:
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "node",
        "sourceMap": true,
        "outDir": "build"
    },
    "exclude": [
        "node_modules",
        "build",
        "config",
        "release"
    ]
}

node_modules is in ./node_modules with all the @types in there ok.

**Comment by jdmonk** [comment]
Just seen update, updated to tslint 4.0.1 and tslint-loader 3.0.0, same issue :)

**Comment by jmlopez-rod** [comment]
@jasdf2351 Does it work if you remove the tslint-loader option?

```js
module.exports = {
  entry: {
    server: './bin/www.ts'
  },
  output: {
    filename: '[name].js',
    path: './build',
    libraryTarget: "commonjs"
  },
  devtool: 'source-map',
  target: 'node',
  externals: [
    /^[a-z-0-9]+$/ // Ignore node_modules folder
  ],
  resolve: {
    // Add in .ts as a resolvable extension.
    extensions: ['.ts'],
  },
  resolveLoader: {
    modules: ['./node_modules']
  },
  module: {
    /* rules: [{
      enforce: 'pre',
      test: /.ts$/,
      loader: 'tslint-loader',
      exclude: /(node_modules)/
    }], */
    loaders: [{
      test: /.ts$/,
      exclude: [/node_modules/],
      loader: 'awesome-typescript-loader'
    }]
  },
  plugins
};
```

Just to make sure this is a problem with the tslint-loader and not with the typescript loader.
I'm not using webpack 2 yet, but in my configuration I have it like this:

```
{ test: /\.ts$/i, loaders: ['ts', 'tslint'], exclude: /node_modules/ },
```

You would have to use `awesome-typescript` instead of `ts` in your case.

**Comment by jasdf2351** [comment]
@jmlopez-rod Thanks for the tip, got it sorted.  The docs have changed slightly since I last read them for the beta, now have:

module.exports = {
    entry: {
        server: './bin/www.ts'
    },
    output: {
        filename: '[name].js',
        path: './build',
        libraryTarget: "commonjs"
    },
    devtool: 'source-map',
    target: 'node',
    externals: [
        /^[a-z\-0-9]+$/ // Ignore node_modules folder
    ],
    resolve: {
        // Add in `.ts` as a resolvable extension.
        extensions: ['.ts'],
        modules: ['./node_modules']
    },
    module: {
        rules: [{
            enforce: 'pre',
            test: /\.ts$/,
            loader: 'tslint-loader',
            exclude: /(node_modules)/
        }, {
            test: /\.ts$/,
            loader: 'awesome-typescript-loader',
            exclude: /(node_modules)/
        }]
    },
    plugins
};

and turned on "no-any": true and it correctly spat out errors, turned it off and it's now passing.

Still does a build despite failOnHint: true being set, might just have to wait that one out do you think?

**Comment by jmlopez-rod** [comment]
So just to be clear, the `no-any` option is from typescript right? It doesn't look like the issue is due to tslint at all then, seems more like an awesome-typescript-loader issue. Try removing the tslint-loader for moment and add several options to typescript, for instance:

```
noUnusedParameters 
noUnusedLocals
```

Then declare some variable and see if your build fails.

**Comment by blacksonic** [comment]
@jasdf2351 Is the ```tslint-loader``` related part resolved then?

**Comment by jmlopez-rod** [comment]
@blacksonic That's what it seems. I think it is safe to close issue unless @jasdf2351 has additional info. Also @jasdf2351 try to format what you post so that it easier for others to read, see https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting.

**Comment by dynamicmonkeys** [comment]
@jmlopez-rod `no-any: true` is a rule from within tslint.json, tslint-loader correctly flags this as it should, a warning, however then webpack continues and does the build, I thought that `failOnHint: true` would stop webpack from continuing to do the build.

Maybe it's a webpack-beta thing and might settle down when you guys have a stable webpack to test against?

Apologies for my lack of Markdown-foo, I've found the preview button :)

**Comment by jasdf2351** [comment]
@jmlopez-rod `no-any: true` is a rule from within tslint.json, tslint-loader correctly flags this as it should, a warning, however then webpack continues and does the build, I thought that `failOnHint: true` would stop webpack from continuing to do the build.

Maybe it's a webpack-beta thing and might settle down when you guys have a stable webpack to test against?

Apologies for my lack of Markdown-foo, I've found the preview button :)

**Comment by blacksonic** [comment]
No tests currently for Webpack beta, only for the stable branch.

**Comment by jasdf2351** [comment]
@blacksonic I saw the test for failOnHint hence why I asked, thought I'd double check.  Thanks for info, closing and will keep an eye out for WP2 hitting, keep up the great work.
