### ISSUE TITLE
typeCheck rules don't allow specifying path to tsconfig.json

### ISSUE THREAD

**Issue by Kovensky** [wbuchwalter/tslint-loader#45]
The typeCheck option added for #36 hardcodes the `tsconfig.json` as being in the `process.cwd()`, which is not the case in a hierarchy like:

```
src/
  tsconfig.json
  index.ts
webpack.config.js
```

The `tsconfig.json` is loaded in the wrong directory (ENOENT).

**Comment by blacksonic** [comment]
Saw this one coming :)
Yes it is hardcoded, will add an option to configure just as the tslint config file.
