### ISSUE TITLE
Enable ESLint

### ISSUE THREAD

**Issue by bhovhannes** [wbuchwalter/tslint-loader#49]
It will be nice to add ESLint to this project.

It is not that big to benefit from ES6, so I don't think we need to bring in additional transpilation step. But having ESLint checks will ensure consistent coding standards for this repo.

Rules may extends `eslint-config-recommended` and use `eslint-env=node`.

**Comment by bhovhannes** [comment]
Pull request #51 closes this one.

Airbnb styleguide includes a lot of rules related with JSX, React and other stuff which is not used here.
In #51 basic ESLint support has been added. I think we can have this as starting point in any case.

**Comment by jmlopez-rod** [comment]
Why not use typescript and tslint?

**Comment by bhovhannes** [comment]
That will require additional transpilation step, which we think is overhead for relatively small amount of code we currently have

**Comment by jmlopez-rod** [comment]
True, an additional step, but as the code grows you have added error checks done by typescript. I wouldn't think so much as typescript having to traspile the code. I like to think more of typescript as as additional error checker. Also, the transpilation doesn't take long.

**Comment by bhovhannes** [comment]
I don't think the code here will grow much. This is the loader for webpack. It does not aim to do complex things. 
I personally use Typescript now in one of mine projects and find it extremely useful for refactoring code. But my code is approx. 50 times longer than the code of this loader, and I don't think we'll gain big benefits from Typescript here. 
Another downside of typescript is that after introducing it you'll bring in remap-Istanbul for correct code coverage, which is not actively maintained and has several nasty issues.
