### ISSUE TITLE
"tslint.json not found" is shown, even if config is set in Webpack configuration

### ISSUE THREAD

**Issue by sebald** [wbuchwalter/tslint-loader#5]
I am loading my configuration with `require` statement:

```javascript
tslint: {
    failOnHint: true,
    configuration: require('./tslint.config.json')
}
```

Linting does work.

**Comment by sebald** [comment]
Also, linting seems to only work correct when loading it via `tslint.json`.

**Comment by Aslate49** [comment]
I'm following the default instructions, without any extra configuration provided by the optional tslint webpack config block and it doesn't seem to pick up anything.

The config file works fine when running tslint / tsfmt manually in the project directory.

**Comment by Aslate49** [comment]
Was being an idiot, my preLoader block was outside of my module block
