### ISSUE TITLE
Use loader with tslint@next

### ISSUE THREAD

**Issue by Strate** [wbuchwalter/tslint-loader#53]
I am fine with typescript@next and tslint@next, but tslint-loader's peerDependency blocks me. As for now I need to maintain fork. Could you either remove peerDependency from this loader, or publish separate version without it?

**Comment by blacksonic** [comment]
Is there a major version bump for them? If no, you can specify the latest version instead of next and it should work.

**Comment by Strate** [comment]
I've played around with tslint and https://semver.npmjs.com/, and found constraint which will fit my requirement: `>=4.0.0-dev`. Could you change this in package.json?
