### ISSUE TITLE
TSLint --fix option cannot be controlled

### ISSUE THREAD

**Issue by mayani** [wbuchwalter/tslint-loader#54]
tslint has a --fix option. There does not seem to be a way to invoke tslint-loader with --fix option.
Code at [https://github.com/wbuchwalter/tslint-loader/blob/master/index.js#L34](https://github.com/wbuchwalter/tslint-loader/blob/master/index.js#L34) had codes it to false.

**Comment by aequasi** [comment]
Fixed by #60

**Comment by blacksonic** [comment]
Fix is out with version `3.4.0`.
