### ISSUE TITLE
Use tslint.json file for configuration?

### ISSUE THREAD

**Issue by sheam** [wbuchwalter/tslint-loader#58]
Is there a way I have can my tslint configuration in a seperate file so other tools may use it as well? Most tooling expects the file to be named tslint.json. I tried 

```
	tslint: {
		failOnHint: true,
	   	require('./tslint.json')
	},
```

But when I run webpack, I get an 'unexpected string' error at the _require_ line.

**Comment by vlio20** [comment]
@sheam , how did you solve this one?

**Comment by sheam** [comment]
```
       tslint: {
		failOnHint: true,
	   	configuration: require('./tslint.json')
	},
```

**Comment by SenHeng** [comment]
for webpack2

```
 {
    test: /\.ts$/,
    enforce: 'pre',
    loader: 'tslint-loader',
    options: {
      configFile: './tslint.json',
      failOnHint: true
    }
```
