### ISSUE TITLE
Mention dependency on tslint

### ISSUE THREAD

**Issue by smartin015** [wbuchwalter/tslint-loader#59]
This may seem obvious, but... tslint-loader depends on tslint, and it is not listed anywhere in documentation. 

The error (`Cannot find module tslint`) sounds almost like tslint-loader is broken and it takes as moment to realize what's actually going on. Could this be listed in a requirements section in the readme?

**Comment by blacksonic** [comment]
`npm install` gives warning for missing `peerDependencies`

**Comment by blacksonic** [comment]
Added it to docs with exact version range.
