### ISSUE TITLE
Warning "Cannot read property 'exports' of undefined" when running with type checking

### ISSUE THREAD

**Issue by Vinnl** [wbuchwalter/tslint-loader#66]
When I enable `typeCheck: true,` in my tslint-loader configuration, Webpack suddenly outputs

> Warning: Cannot read property 'exports' of undefined

I'm not running into this when I simply run `tslint --project tsconfig.json --type-check`.

Unfortunately, there's not much more info, but if there's any relevant debugging information I can gather, let me know.

**Comment by blacksonic** [comment]
@Vinnl do you have any stacktrace?

**Comment by Vinnl** [comment]
@blacksonic No, this was the only output. Do you happen to know if and how I can enable more verbose debug output?

**Comment by blacksonic** [comment]
No idea, but can you make an example repository?

**Comment by Vinnl** [comment]
That's a bit too much work for me, especially given that I've no idea what specifically could've caused this and thus what would need to be in such a repo. If there's any way I can gather more information from my existing setup I'm willing to try, but otherwise I'm closing this.

(Unless @jdolle still wants to try, given that they've given this issue a +1.)
