### ISSUE TITLE
Tslint should be of version 4+

### ISSUE THREAD

**Issue by sentika** [wbuchwalter/tslint-loader#67]
I tried to update tslint to version 5.0.0, but I got an error on build

ERROR in ./src/polyfills.browser.ts
Module build failed: Error: Tslint should be of version 4+
    at Object.module.exports (\node_modules\tslint-loader\index.js:121:11)
 @ multi (webpack)-dev-server/client?./src/polyfills.browser.ts

version of tslint-loader: 3.4.3

**Comment by CarlosV89** [comment]
Happening to me as well

**Comment by Ketec** [comment]
Same - it does not work with 5.0.0 anymore.

**Comment by blacksonic** [comment]
There is a check for the version in code to avoid other mysterious crashes.
It is also inside `package.json`

```
"peerDependencies": {
  "tslint": "^4.0.0"
}
```

You can upgrade it in the repo and submit a pull request. It would cause a major version change in `tslint-loader`.

**Comment by skiabox** [comment]
I confirm that I get the same error!

**Comment by arthrmlo** [comment]
If you updated your project and your build is breaking, just rollback to the latest TSLint 4 version (4.5.1) and it will work fine. That's the only alternative until upstream update.

**Comment by blacksonic** [comment]
It should work now with version 3.5.1
