### ISSUE TITLE
Write lint output to file?

### ISSUE THREAD

**Issue by joshuacc** [wbuchwalter/tslint-loader#7]
I've looked over the documentation and didn't see this option, but please let me know if I just missed it.

It would be great if the loader could write lint output to a file for use on a CI server. I'd be happy to submit a pull request adding this functionality.

Thoughts?

**Comment by wbuchwalter** [comment]
It's currently not supported, but that would be a great feature.
PR most welcome!
Thanks.

**Comment by wbuchwalter** [comment]
Closed with #13, released on npm in `2.1.0`

**Comment by joshuacc** [comment]
Awesome. Thanks!
