### ISSUE TITLE
Update to tslint@3.0.0

### ISSUE THREAD

**Issue by zdychacek** [wbuchwalter/tslint-loader#8]
Hi,

pls update tslint dependency to v3.0.0.

Thx.

O.

**Comment by punya** [comment]
It would be even better if `tslint-loader` could take a [peer dependency](https://nodejs.org/en/blog/npm/peer-dependencies/) on `tslint` instead of locking in a specific version. That's how `tslint` depends on `typescript`, for example.

**Comment by adidahiya** [comment]
+1 for peer dependency

**Comment by wbuchwalter** [comment]
@punya Makes sense indeed. Will do that. Sorry for the delay, I don't have a lot of time these days.
Thanks.

**Comment by wbuchwalter** [comment]
Fixed in #11.
