### ISSUE TITLE
Bundle all errors as tslint.report.xml

### ISSUE THREAD

**Issue by JonWallsten** [wbuchwalter/tslint-loader#93]
Not sure if I'm doing something wrong. Is it possible to get a single tslint.report.xml file instead of a folder structure with each file that fails. I need a singe file for Jenkins.

**Comment by sextos3** [comment]
Shouldn't really be needed. For example:

```
loader: 'tslint-loader',
options: {
  typeCheck: false,
  formatter: 'checkstyle',
  formattersDirectory: 'node_modules/tslint/lib/formatters',
  fileOutput: {
    dir: 'reports',
    ext: 'xml'
  }
}
```

With Jenkins check style plugin, all you have to do is point to the wildcard location for these files: reports/app/**/**.xml, and it'll report across all of the issues.

**Comment by JonWallsten** [comment]
Ah, perfect! Thanks!
