### ISSUE TITLE
Support webpack 4

### ISSUE THREAD

**Issue by jaketodaro** [wbuchwalter/tslint-loader#97]
Webpack 4 is out. All my other loaders have updated, but this one is keeping me from upgrading. 

https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202

**Comment by Kimahriman** [comment]
This loader has already been fixed for Webpack 4, but there's been no new release of it. You can install it directly from github if you want to upgrade now

```
npm i -D wbuchwalter/tslint-loader
```

**Comment by jaketodaro** [comment]
Thanks, I'll close. When will the next release be?
