### ISSUE TITLE
Release new version with fix for webpack 4

### ISSUE THREAD

**Issue by Bobo1239** [wbuchwalter/tslint-loader#98]
https://github.com/wbuchwalter/tslint-loader/pull/95 fixed support for webpack 4 which was still a RC by then. Now that it's officially released, tslint-loader should also release a new version with the fix included.

**Comment by giorgiomarcias** [comment]
+1

**Comment by blacksonic** [comment]
New version is out: 3.6.0

**Comment by Bobo1239** [comment]
@blacksonic Thanks for that quick response. :+1:

**Comment by anshul119** [comment]
@blacksonic you should change the version in package.json as well :)

**Comment by blacksonic** [comment]
@anshul119 which one?

**Comment by anshul119** [comment]
The current version of tslint-loader is 3.6.0 but inside package.json it says 3.5.3 :) I was a bit confused for a while
